spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/FormerDetails
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 8200